Updated workflow for dynamic values

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -250,6 +250,18 @@ jobs:
           GIT_COMMIT: ${{ github.sha }}
           GIT_REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
         run: |
+          DYNAMIC_PARAMS="DDGitData='${GIT_COMMIT},${GIT_REPO_URL}' Version='${VERSION}'"
+
+          if ! yq eval ".\"${{ matrix.stack }}".deploy.parameters.parameter_overrides" samconfig.yaml >/dev/null; then
+            echo "[WARN] parameter_overrides not found, initialising key"
+            yq eval -i ".\"${{ matrix.stack }}".deploy.parameters.parameter_overrides = \"\"" samconfig.yaml
+          fi
+
+          EXISTING_PARAMS=$(yq eval ".\"${{ matrix.stack }}".deploy.parameters.parameter_overrides" samconfig.yaml)
+          UPDATED_PARAMS="${EXISTING_PARAMS} ${DYNAMIC_PARAMS}"
+
+          yq eval -i ".\"${{ matrix.stack }}".deploy.parameters.parameter_overrides = \"${UPDATED_PARAMS}\"" samconfig.yaml
+
           sam deploy \
             --template-file packaged.yaml \
             --stack-name ${{ steps.get-stack.outputs.result }} \
@@ -258,11 +270,11 @@ jobs:
             --no-confirm-changeset \
             --no-fail-on-empty-changeset \
             --s3-bucket $RC_SRC --s3-prefix bods-backend/deployments/${{ matrix.stack }} \
-            --parameter-overrides ParameterKey=DDGitData,ParameterValue="${GIT_COMMIT},${GIT_REPO_URL}" ParameterKey=Version,ParameterValue=${VERSION} \
             --tags "BuiltFrom=${VERSION} version=${VERSION} ProjectName=${{ vars.PROJECT_NAME }} Environment=${RC_ENV} AppManagerCFNStackKey=${{ steps.get-stack.outputs.result }}"
           echo "[INFO] Application with version [${VERSION}] successfully deployed into ${RC_ENV^^} for ${{ matrix.stack }}"
 
       - name: update confluence page
+        if: ${{ matrix.stack == 'dev' }}
         uses: robsteel24/update-confluence@v1
         with:
           confluence_base_url: ${{ vars.CONFLUENCE_BASE_URL }}
